// Auto-generated by Supabase — do not edit by hand.
// Regenerate with: npx supabase gen types typescript --project-id btlhjcdwlvgzqcfxfqwd

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      meetup_requests: {
        Row: {
          activity: string
          admin_notes: string | null
          created_at: string
          email: string
          end_time: string | null
          id: string
          location: string | null
          message: string
          name: string
          start_time: string | null
          status: string
          venue_id: string | null
        }
        Insert: {
          activity: string
          admin_notes?: string | null
          created_at?: string
          email: string
          end_time?: string | null
          id?: string
          location?: string | null
          message: string
          name: string
          start_time?: string | null
          status?: string
          venue_id?: string | null
        }
        Update: {
          activity?: string
          admin_notes?: string | null
          created_at?: string
          email?: string
          end_time?: string | null
          id?: string
          location?: string | null
          message?: string
          name?: string
          start_time?: string | null
          status?: string
          venue_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "meetup_requests_venue_id_fkey"
            columns: ["venue_id"]
            isOneToOne: false
            referencedRelation: "venues"
            referencedColumns: ["id"]
          },
        ]
      }
      request_comments: {
        Row: {
          author: string
          body: string
          created_at: string
          id: string
          request_id: string
        }
        Insert: {
          author?: string
          body: string
          created_at?: string
          id?: string
          request_id: string
        }
        Update: {
          author?: string
          body?: string
          created_at?: string
          id?: string
          request_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "request_comments_request_id_fkey"
            columns: ["request_id"]
            isOneToOne: false
            referencedRelation: "meetup_requests"
            referencedColumns: ["id"]
          },
        ]
      }
      trusted_emails: {
        Row: {
          created_at: string
          email: string
          id: string
          label: string | null
        }
        Insert: {
          created_at?: string
          email: string
          id?: string
          label?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          id?: string
          label?: string | null
        }
        Relationships: []
      }
      venues: {
        Row: {
          address: string | null
          area: string | null
          created_at: string
          id: string
          name: string
          notes: string | null
          type: string | null
          url: string | null
        }
        Insert: {
          address?: string | null
          area?: string | null
          created_at?: string
          id?: string
          name: string
          notes?: string | null
          type?: string | null
          url?: string | null
        }
        Update: {
          address?: string | null
          area?: string | null
          created_at?: string
          id?: string
          name?: string
          notes?: string | null
          type?: string | null
          url?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends { Insert: infer I }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends { Update: infer U }
      ? U
      : never
    : never
